import React from "react";
import * as _Builtin from "./_Builtin";
import * as _utils from "./utils";
import _styles from "./Footer.module.css";

export function Footer({ as: _Component = _Builtin.Block }) {
  return (
    <_Component className={_utils.cx(_styles, "footer")} tag="footer">
      <_Builtin.Container className={_utils.cx(_styles, "container")} tag="div">
        <_Builtin.Block tag="div">
          <_Builtin.Block tag="div">
            {
              "© 2023 Rock, Paper, Scissors Dev | All Rights Reserved | All content generated by Chat GPT | "
            }
            <_Builtin.Link
              className={_utils.cx(_styles, "footer-link")}
              button={false}
              options={{
                href: "#",
              }}
            >
              {"Report issue"}
            </_Builtin.Link>
          </_Builtin.Block>
        </_Builtin.Block>
      </_Builtin.Container>
    </_Component>
  );
}
